/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as senderSol from "./Sender.sol";
export type { senderSol };
export type { Receiver } from "./Receiver";
