export const SENDER_ADDRESS = process.env.NEXT_PUBLIC_SENDER_ADDRESS!;
export const RECEIVER_ADDRESS = process.env.NEXT_PUBLIC_RECEIVER_ADDRESS!;
export const OPTIMISM_ETHERSCAN_BASE =
  process.env.NEXT_PUBLIC_OPTIMISM_EXPLORER_BASE!;
export const SEPOLIA_ETHERSCAN_BASE =
  process.env.NEXT_PUBLIC_SEPOLIA_EXPLORER_BASE!;
export const OPTIMISM_RPC_URL = process.env.NEXT_PUBLIC_OPTIMISM_RPC_URL!;
export const SEPOLIA_RPC_URL = process.env.NEXT_PUBLIC_SEPOLIA_RPC_URL!;
