/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IL1CrossDomainMessenger } from "./IL1CrossDomainMessenger";
export type { Sender } from "./Sender";
