/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ReceiverInterface extends Interface {
  getFunction(nameOrSignature: "handleMessage"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Message"): EventFragment;

  encodeFunctionData(
    functionFragment: "handleMessage",
    values: [AddressLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "handleMessage",
    data: BytesLike
  ): Result;
}

export namespace MessageEvent {
  export type InputTuple = [sender: AddressLike, text: string];
  export type OutputTuple = [sender: string, text: string];
  export interface OutputObject {
    sender: string;
    text: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Receiver extends BaseContract {
  connect(runner?: ContractRunner | null): Receiver;
  waitForDeployment(): Promise<this>;

  interface: ReceiverInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  handleMessage: TypedContractMethod<
    [sender: AddressLike, text: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "handleMessage"
  ): TypedContractMethod<
    [sender: AddressLike, text: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Message"
  ): TypedContractEvent<
    MessageEvent.InputTuple,
    MessageEvent.OutputTuple,
    MessageEvent.OutputObject
  >;

  filters: {
    "Message(address,string)": TypedContractEvent<
      MessageEvent.InputTuple,
      MessageEvent.OutputTuple,
      MessageEvent.OutputObject
    >;
    Message: TypedContractEvent<
      MessageEvent.InputTuple,
      MessageEvent.OutputTuple,
      MessageEvent.OutputObject
    >;
  };
}
